Implement Get By Application Endpoint
LBHackney-IT/developer-hub-api pull request #13
Opened 2022-02-02 16:05 UTC by lbhMichael

## Link to JIRA ticket

Add a link to the JIRA ticket that the changes in this PR describe.

## Describe this PR

### *What is the problem we're trying to solve*

Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.

### *What changes have we introduced*

Add descriptions of what changes were made to address the problem and provide a solution.

Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.

#### _Checklist_

- [ ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [ ] Added tests to cover all new production code
- [ ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [ ] Checked all code for possible refactoring
- [ ] Code pipeline builds correctly

### *Follow up actions after merging PR*

Are there any next steps that need to addressed after merging this PR? Add them here.

2022-02-03 12:24 UTC, humulla requested changes
- Please remove [this empty use case test class](DeveloperHubAPI.Tests/V1/UseCase/DeveloperHubApi.cs) 
- Can you update the entity factory tests and response factory tests to test the new fields that you have added

2022-02-03 12:24 UTC, humulla commented on DeveloperHubAPI/V1/Gateways/DynamoDbGateway.cs
> +        public async Task<DevelopersHubApi> GetDeveloperHubById(string id)
Why has the parameter been changed from `DeveloperHubQuery query` to `string id`?

2022-02-03 12:24 UTC, humulla commented on DeveloperHubAPI/V1/Infrastructure/DatabaseEntity.cs
>  namespace DeveloperHubAPI.V1.Infrastructure
Can we rename the file name to be `DeveloperHubDb` please

2022-02-03 12:24 UTC, humulla commented on DeveloperHubAPI/V1/UseCase/GetDeveloperHubByIdUseCase.cs
> +            throw new NotImplementedException();
Why is this method throwing an exception?

2022-02-03 12:24 UTC, humulla commented on DeveloperHubAPI/V1/Factories/ResponseFactory.cs
> +        public static ApplicationResponse ToResponse(this Application domain)
Rather than creating a new method can we not update the `DeveloperHubResponse ToResponse(this DevelopersHubApi domain)` method with the ApplicationList. So something like:
`Applications = domain.Applications.ToList()`

2022-02-03 14:24 UTC, notatiyyah commented on DeveloperHubAPI/V1/Gateways/DynamoDbGateway.cs
> +        public async Task<DevelopersHubApi> GetDeveloperHubById(string id)
This is so that we can use the same Gateway function in both usecases, rather than using the query (which just has Id in it anyway), it uses ID instead.

2022-02-03 14:26 UTC, notatiyyah commented on DeveloperHubAPI/V1/Factories/ResponseFactory.cs
> +        public static ApplicationResponse ToResponse(this Application domain)
According to the [swagger docs](https://app.swaggerhub.com/apis/Hackney/DeveloperHubAPI/1.0.0#/default/get__id___applicationName_), this endpoint just returns the application details, so we need a separate response object for it!

2022-02-07 10:35 UTC, notatiyyah commented on DeveloperHubAPI/V1/UseCase/GetDeveloperHubByIdUseCase.cs
> +            throw new NotImplementedException();
Removed!

2022-02-07 10:36 UTC, notatiyyah commented on DeveloperHubAPI/V1/Infrastructure/DatabaseEntity.cs
>  namespace DeveloperHubAPI.V1.Infrastructure
Done!

2022-02-07 10:43 UTC, humulla approved these changes
Looks good to me :)

2022-02-07 11:29 UTC, merged