Adding new application endpoint
LBHackney-IT/developer-hub-api pull request #17
Opened 2022-02-23 17:10 UTC by elena-evans

## Link to JIRA ticket

https://trello.com/c/kjzjcehP/84-implement-patch-by-application-endpoint

## Describe this PR

### *What is the problem we're trying to solve*

Add a new application to the list to show it uses a particular API

### *What changes have we introduced*

Add descriptions of what changes were made to address the problem and provide a solution.

Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.

#### _Checklist_

- [ ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [ ] Added tests to cover all new production code
- [ ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [ ] Checked all code for possible refactoring
- [ ] Code pipeline builds correctly

### *Follow up actions after merging PR*

Are there any next steps that need to addressed after merging this PR? Add them here.

2022-02-28 11:16 UTC, humulla requested changes
It looks you have done a POST request rather than a PATCH, please update the code and filenames so that it is a PATCH request (we don't need a POST request). Here is the swagger link you can refer to:
https://app.swaggerhub.com/apis/Hackney/DeveloperHubAPI/1.0.0#/default/patch__id___applicationName_

2022-02-28 11:16 UTC, humulla commented on DeveloperHubAPI/V1/Controllers/DeveloperHubAPIController.cs
> +        [HttpPost]
It should be a PATCH request rather than POST

2022-02-28 11:16 UTC, humulla commented on DeveloperHubAPI/V1/UseCase/CreateNewApplicationUseCase.cs
> +    public class CreateNewApplicationUseCase : ICreateNewApplicationUseCase
Let's call the usecase `UpdateApplicationUseCase` as it is a PATCH request

2022-03-01 16:46 UTC, elena-evans commented
@humulla I have made the changes to make this a patch endpoint, please could you review again? Thanks!

2022-03-02 11:16 UTC, humulla commented on DeveloperHubAPI.Tests/V1/Controllers/DeveloperHubAPIControllerTests.cs
> +            response.Should().BeOfType(typeof(NotFoundObjectResult));
Can you add another assertion to ensure that the id that is notFound is provided as part of the object result.

2022-03-02 11:16 UTC, humulla commented on DeveloperHubAPI.Tests/V1/UseCase/CreateNewApplicationUseCaseTests.cs
> +        public async Task AddsApplicationToAPI()
```suggestion
        public async Task AddsApplicationToAPISuccessfully()
```

2022-03-02 11:16 UTC, humulla commented on DeveloperHubAPI.Tests/V1/UseCase/CreateNewApplicationUseCaseTests.cs
> +    public class UpdateApplicationUseCaseTests : LogCallTestContext
It looks like you have only changed the Namespace, please also update the filename.

2022-03-02 15:23 UTC, humulla approved these changes

2022-03-02 15:29 UTC, merged