Feature delete endpoint
LBHackney-IT/developer-hub-api pull request #19
Opened 2022-03-09 11:26 UTC by 1JW1

## Describe this PR

### *What is the problem we're trying to solve*

An endpoint for deletion was required so that we can delete an application from a list, if it no longer consumes the API it is referenced in.

### *What changes have we introduced*

Response objects created along with a new use case. The gateway and controller had new methods and endpoints added to them respectively. Tests were also created for the new code. Lastly, a global secondary index was added to the dynamodb terraforms for all three stages.

#### _Checklist_

- [x] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [x] Added tests to cover all new production code
- [x] Checked all code for possible refactoring
- [x] Code pipeline builds correctly

2022-03-09 11:39 UTC, notatiyyah requested changes

2022-03-09 11:39 UTC, notatiyyah commented on terraform/development/dynamodb.tf
> +    global_secondary_index {
I'm confused why we're adding a GSI when it's not necessary?
The only thing we're using to query the DB is the API ID, which doesn't need a GSI.

2022-03-09 11:49 UTC, 1JW1 commented on terraform/development/dynamodb.tf
> +    global_secondary_index {
I was thinking the same initially when I read about it but havent had the chance to question it as the lead has been away. Thought it might be an addition to accommodate the scaling up of the project in the future. I can remove for now if its too much of a question mark and add back in if there's a strong reason for it, at a later date.

2022-03-09 12:08 UTC, notatiyyah commented on terraform/development/dynamodb.tf
> +    global_secondary_index {
Are we planning to look up APIs by applications? (E.g. list all APIs used by repairs hub). That's one reason we may want to set it up, but this is not in scope for this ticket.

2022-03-09 12:13 UTC, 1JW1 commented on terraform/development/dynamodb.tf
> +    global_secondary_index {
I think your comment about scope is an important one that I agree with. Ill remove it for now since its absence won't have an influence on what we need for now and ill add it to the board as talking point for a later date.

2022-03-10 14:40 UTC, notatiyyah commented on DeveloperHubAPI.Tests/V1/E2ETests/DeleteApplicationByName.cs
> +            var responseContent = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
I don't think we need to return anything from the delete endpoint other than the status code, following the [swagger doc](https://app.swaggerhub.com/apis/Hackney/DeveloperHubAPI/1.0.0#/default/delete__id___applicationName_)

2022-03-10 14:40 UTC, notatiyyah commented on DeveloperHubAPI.Tests/V1/Gateways/DynamoDbGatewayTests.cs
>          public async Task SaveDeveloperHubSuccessfullySavesTheEntity()
Why was this removed?

2022-03-10 14:59 UTC, 1JW1 commented on DeveloperHubAPI.Tests/V1/Gateways/DynamoDbGatewayTests.cs
>          public async Task SaveDeveloperHubSuccessfullySavesTheEntity()
good spot. I've added the attribute back and the test passes. Will commit once ive addressed your previous comment

2022-03-10 15:08 UTC, 1JW1 commented on DeveloperHubAPI.Tests/V1/E2ETests/DeleteApplicationByName.cs
> +            var responseContent = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
I thought that this is additional confirmation of the OK status that you would need to show for a thorough E2E. Does line 52 mean its thorough enough? I Can remove lines 60 - 63 if that's the case.

2022-03-14 15:16 UTC, humulla approved these changes

2022-03-14 16:24 UTC, notatiyyah approved these changes

2022-03-14 16:29 UTC, merged